---
title: "wr"
output: html_notebook
---
```{r Hochladen der Listen für das Netzwerk}
 
library(igraph)
# load raw edges data ----
edgelist <- read.csv("https://raw.githubusercontent.com/weisse-rose/Weisse-Rose/master/edgelist.csv",header=T, as.is=T, sep=",")

# load raw nodes data ----
nodelist <- read.csv("https://raw.githubusercontent.com/weisse-rose/Weisse-Rose/master/nodelist.csv",header=T, as.is=T, sep=",")

# Überprüfen der Daten
head(edgelist)
head(nodelist)

# create network ----
edges <- as.matrix(edgelist)
nodes <- as.matrix(nodelist)
wr <-  graph_from_data_frame(d=edges,vertices=nodelist, directed=F)
plot(wr, main="Gesamtnetzwerk Weiße Rose")
```

```{r Auswahl Edge-Attribute}

list.edge.attributes(wr)
E(wr)$arrow.size <- .2 # definiert die Pfeilspitze auf Größe .2
E(wr)$curved <- .2 # definiert die Krümmung der Kanten
list.edge.attributes(wr) # zeigt die neu definierten Attribute an.
edge.attributes(wr)$relationship
edge.attributes(wr)$time
```

```{r Visualisierung nach Edge-Attribut time1}

# setzt den Wert rot für alle Werte 1 = vor Flugblatt 1 ---
edge.attributes(wr)$time
plot(wr, edge.color=c("red", "black")[(E(wr)$time=="1")+1], main="Gesamtnetzwerk Weiße Rose", sub="Beziehungen vor Flugblatt 1 sind rot gekennzeichnet")
```

```{r Visualisierung nach Edge-Attribut time 2}

# setzt den Wert rot für alle Werte 2 = Flugblatt 1 ---
edge.attributes(wr)$time
plot(wr, edge.color=c("red", "black")[(E(wr)$time=="2")+1], main="Gesamtnetzwerk Weiße Rose", sub="Beziehungen während Flugblatt 1 sind rot gekennzeichnet")

```

```{r Visualisierung nach Edge-Attribut time 10}

# setzt den Wert rot für alle nach Wert 10 = Flugblatt 1-4 ---
edge.attributes(wr)$time
plot(wr, edge.color=c("red", "black")[(E(wr)$time=="10")+1], main="Gesamtnetzwerk Weiße Rose", sub="Beziehungen während Flugblätter 1-4 sind rot gekennzeichnet")
```


```{r Auswahl Vertex-Attribute}

list.vertex.attributes(wr)
vertex.attributes(wr)$name
vertex.attributes(wr)$sex
vertex.attributes(wr)$age
vertex.attributes(wr)$hometown
vertex.attributes(wr)$occupation
```

```{r Visualisierung Vertex-Attribut sex}

# setzt den Wert blau für sex 1 und orange für sex 2 ein
vertex.attributes(wr)$sex
V(wr)[V(wr)$sex=="1"]$color <- "lightblue"
V(wr)[V(wr)$sex=="2"]$color <- "orange"
plot(wr, 
     layout=layout_nicely, 
     main="Gesamtnetzwerk Weiße Rose",
     sub="Vertex-Attribute: sex 1 (männlich) = lightblue, sex 2 (weiblich) = orange")
```

```{r Visualisierung Vertex-Attribut hometown}

# setzt den Wert blau=München(1), rot=Ulm(3), grün=Hamburg(4), pink=Stuttgart(7) ein
vertex.attributes(wr)$hometown
V(wr)[V(wr)$hometown=="1"]$color <- "blue"
V(wr)[V(wr)$hometown=="3"]$color <- "red"
V(wr)[V(wr)$hometown=="4"]$color <- "green"
V(wr)[V(wr)$hometown=="7"]$color <- "yellow"
plot(wr, 
     layout=layout_nicely, 
     main="Gesamtnetzwerk Weiße Rose",
     sub="Vertex-Attribut hometown blau=München, rot=Ulm, grün=Hamburg, yellow=Stuttgart")
```

```{r Cluster}

# Vorbereitung für Cluster-Berechnung
?cluster_walktrap
wr
gc <- cluster_walktrap(wr)
modularity(gc)
membership(gc)
par(mfrow=c(1,1), mar=c(0,0,1,2))
plot(gc, wr, edge.arrow.size=.2, main="Clusteranalyse des Gesamtnetzwerks")

```

```{r Berechnung der degrees}

degree(wr)
```

```{r Ego-Netzwerk Hans Scholl}

# ego_size() zeigt uns den Wert mit den höchsten Verbindungen (degrees)
V(wr)$egos <- ego_size(wr)
vertex.attributes(wr)$egos
which.max(vertex.attributes(wr)$egos)

## Code zur Erzeugung des Egonetzwerks
wr
ego1 <- make_ego_graph(wr, order = 1, nodes = V(wr)$name == "hans scholl", mode ="all")
ego1[[1]]
plot(ego1[[1]], main="Ego-Netzwerk von Hans Scholl")
```

```{r Ego-Netzwerk Willi Graf}

V(wr)$egos <- ego_size(wr)
vertex.attributes(wr)$egos

## Code zur Erzeugung des Egonetzwerks
wr
ego2 <- make_ego_graph(wr, order = 1, nodes = V(wr)$name == "willi graf", mode ="all")
ego2[[1]]
plot(ego2[[1]], main="Ego-Netzwerk von Willi Graf")
```

```{r Ego-Netzwerk Sophie Scholl}

V(wr)$egos <- ego_size(wr)
vertex.attributes(wr)$egos

## Code zur Erzeugung des Egonetzwerks
wr
ego2 <- make_ego_graph(wr, order = 1, nodes = V(wr)$name == "sophie scholl", mode ="all")
ego2[[1]]
plot(ego2[[1]], main="Ego-Netzwerk von Sophie Scholl")
```

```{r Ego-Netzwerk Alexander Schmorell}

V(wr)$egos <- ego_size(wr)
vertex.attributes(wr)$egos

## Code zur Erzeugung des Egonetzwerks
wr
ego2 <- make_ego_graph(wr, order = 1, nodes = V(wr)$name == "alexander schmorell", mode ="all")
ego2[[1]]
plot(ego2[[1]], main="Ego-Netzwerk von Alexander Schmorell")
```

```{r Ego-Netzwerk Kurt Huber}

V(wr)$egos <- ego_size(wr)
vertex.attributes(wr)$egos

## Code zur Erzeugung des Egonetzwerks
wr
ego2 <- make_ego_graph(wr, order = 1, nodes = V(wr)$name == "kurt huber", mode ="all")
ego2[[1]]
plot(ego2[[1]], main="Ego-Netzwerk von Kurt Huber")
```

```{r Ego-Netzwerk Christoph Probst}

V(wr)$egos <- ego_size(wr)
vertex.attributes(wr)$egos

## Code zur Erzeugung des Egonetzwerks
wr
ego2 <- make_ego_graph(wr, order = 1, nodes = V(wr)$name == "christoph probst", mode ="all")
ego2[[1]]
plot(ego2[[1]], main="Ego-Netzwerk von Christoph Probst")
```

```{r Netzwerk entzerren}
# Netzwerk nochmals neu einlesen

edgelist <- read.csv("https://raw.githubusercontent.com/weisse-rose/Weisse-Rose/master/edgelist.csv",header=T, as.is=T, sep=",")
nodelist <- read.csv("https://raw.githubusercontent.com/weisse-rose/Weisse-Rose/master/nodelist.csv",header=T, as.is=T, sep=",")
edgematrix <-as.matrix(edges)
wr1 <- graph_from_data_frame(d=edgematrix, vertices=nodelist, directed=T)
wr1

# layout parameter festlegen für Fruchterman-Rheingold

l <- layout_with_fr(wr)
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)

par(mfrow=c(2,2), mar=c(0,0,0,0))
plot(wr1, rescale=F, layout=l*0.4, main="Faktor 0.4")
plot(wr1, rescale=F, layout=l*0.8, main="Faktor 0.8")
plot(wr1, rescale=F, layout=l*1.2, main="Faktor 1.2")
plot(wr1, rescale=F, layout=l*2.2, main="Faktor 2.2")

# Beste Visualisierung ist mit Faktor 2.2
par(mfrow=c(1,1), mar=c(1,1,1,1))
plot(wr1, rescale=F, layout=l*2.2, main="entzerrte Darstellung")
```

